networks:
  internal-network:
    driver: bridge

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rails_event_manager_development
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - internal-network

  api:
    build:
      context: .
    command: sh -c "bin/rails db:migrate && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - internal-network 